import * as WEATHERS from './consts/weathers'
import * as REGIONS from './consts/regions'
import * as ZONES from './consts/zones'
import EorzeaWeather from './EorzeaWeather'

EorzeaWeather.WEATHER_BLIZZARDS = WEATHERS.WEATHER_BLIZZARDS
EorzeaWeather.WEATHER_CLEAR_SKIES = WEATHERS.WEATHER_CLEAR_SKIES
EorzeaWeather.WEATHER_CLOUDS = WEATHERS.WEATHER_CLOUDS
EorzeaWeather.WEATHER_DUST_STORMS = WEATHERS.WEATHER_DUST_STORMS
EorzeaWeather.WEATHER_FAIR_SKIES = WEATHERS.WEATHER_FAIR_SKIES
EorzeaWeather.WEATHER_FOG = WEATHERS.WEATHER_FOG
EorzeaWeather.WEATHER_GALES = WEATHERS.WEATHER_GALES
EorzeaWeather.WEATHER_GLOOM = WEATHERS.WEATHER_GLOOM
EorzeaWeather.WEATHER_HEAT_WAVES = WEATHERS.WEATHER_HEAT_WAVES
EorzeaWeather.WEATHER_RAIN = WEATHERS.WEATHER_RAIN
EorzeaWeather.WEATHER_SHOWERS = WEATHERS.WEATHER_SHOWERS
EorzeaWeather.WEATHER_SNOW = WEATHERS.WEATHER_SNOW
EorzeaWeather.WEATHER_THUNDER = WEATHERS.WEATHER_THUNDER
EorzeaWeather.WEATHER_THUNDERSTORMS = WEATHERS.WEATHER_THUNDERSTORMS
EorzeaWeather.WEATHER_UMBRAL_STATIC = WEATHERS.WEATHER_UMBRAL_STATIC
EorzeaWeather.WEATHER_UMBRAL_WIND = WEATHERS.WEATHER_UMBRAL_WIND
EorzeaWeather.WEATHER_WIND = WEATHERS.WEATHER_WIND
EorzeaWeather.REGION_EUREKA = REGIONS.REGION_EUREKA
EorzeaWeather.REGION_GYR_ABANIA = REGIONS.REGION_GYR_ABANIA
EorzeaWeather.REGION_ISHGARD_AND_SURROUNDING_AREAS = REGIONS.REGION_ISHGARD_AND_SURROUNDING_AREAS
EorzeaWeather.REGION_LA_NOSCEA = REGIONS.REGION_LA_NOSCEA
EorzeaWeather.REGION_NORVRANDT = REGIONS.REGION_NORVRANDT
EorzeaWeather.REGION_OTHERS = REGIONS.REGION_OTHERS
EorzeaWeather.REGION_THANALAN = REGIONS.REGION_THANALAN
EorzeaWeather.REGION_THE_BLACK_SHROUD = REGIONS.REGION_THE_BLACK_SHROUD
EorzeaWeather.REGION_THE_FAR_EAST = REGIONS.REGION_THE_FAR_EAST
EorzeaWeather.ZONE_AMH_ARAENG = ZONES.ZONE_AMH_ARAENG
EorzeaWeather.ZONE_AZYS_LLA = ZONES.ZONE_AZYS_LLA
EorzeaWeather.ZONE_CENTRAL_SHROUD = ZONES.ZONE_CENTRAL_SHROUD
EorzeaWeather.ZONE_CENTRAL_THANALAN = ZONES.ZONE_CENTRAL_THANALAN
EorzeaWeather.ZONE_COERTHAS_CENTRAL_HIGHLANDS = ZONES.ZONE_COERTHAS_CENTRAL_HIGHLANDS
EorzeaWeather.ZONE_COERTHAS_WESTERN_HIGHLANDS = ZONES.ZONE_COERTHAS_WESTERN_HIGHLANDS
EorzeaWeather.ZONE_EAST_SHROUD = ZONES.ZONE_EAST_SHROUD
EorzeaWeather.ZONE_EASTERN_LA_NOSCEA = ZONES.ZONE_EASTERN_LA_NOSCEA
EorzeaWeather.ZONE_EASTERN_THANALAN = ZONES.ZONE_EASTERN_THANALAN
EorzeaWeather.ZONE_EULMORE = ZONES.ZONE_EULMORE
EorzeaWeather.ZONE_EUREKA_ANEMOS = ZONES.ZONE_EUREKA_ANEMOS
EorzeaWeather.ZONE_EUREKA_HYDATOS = ZONES.ZONE_EUREKA_HYDATOS
EorzeaWeather.ZONE_EUREKA_PAGOS = ZONES.ZONE_EUREKA_PAGOS
EorzeaWeather.ZONE_EUREKA_PYROS = ZONES.ZONE_EUREKA_PYROS
EorzeaWeather.ZONE_GRIDANIA = ZONES.ZONE_GRIDANIA
EorzeaWeather.ZONE_IDYLLSHIRE = ZONES.ZONE_IDYLLSHIRE
EorzeaWeather.ZONE_IL_MHEG = ZONES.ZONE_IL_MHEG
EorzeaWeather.ZONE_ISHGARD = ZONES.ZONE_ISHGARD
EorzeaWeather.ZONE_KHOLUSIA = ZONES.ZONE_KHOLUSIA
EorzeaWeather.ZONE_KUGANE = ZONES.ZONE_KUGANE
EorzeaWeather.ZONE_LAKELAND = ZONES.ZONE_LAKELAND
EorzeaWeather.ZONE_LIMSA_LOMINSA = ZONES.ZONE_LIMSA_LOMINSA
EorzeaWeather.ZONE_LOWER_LA_NOSCEA = ZONES.ZONE_LOWER_LA_NOSCEA
EorzeaWeather.ZONE_MIDDLE_LA_NOSCEA = ZONES.ZONE_MIDDLE_LA_NOSCEA
EorzeaWeather.ZONE_MIST = ZONES.ZONE_MIST
EorzeaWeather.ZONE_MOR_DHONA = ZONES.ZONE_MOR_DHONA
EorzeaWeather.ZONE_NORTH_SHROUD = ZONES.ZONE_NORTH_SHROUD
EorzeaWeather.ZONE_NORTHERN_THANALAN = ZONES.ZONE_NORTHERN_THANALAN
EorzeaWeather.ZONE_OUTER_LA_NOSCEA = ZONES.ZONE_OUTER_LA_NOSCEA
EorzeaWeather.ZONE_RHALGRS_REACH = ZONES.ZONE_RHALGRS_REACH
EorzeaWeather.ZONE_SHIROGANE = ZONES.ZONE_SHIROGANE
EorzeaWeather.ZONE_SOUTH_SHROUD = ZONES.ZONE_SOUTH_SHROUD
EorzeaWeather.ZONE_SOUTHERN_THANALAN = ZONES.ZONE_SOUTHERN_THANALAN
EorzeaWeather.ZONE_THE_AZIM_STEPPE = ZONES.ZONE_THE_AZIM_STEPPE
EorzeaWeather.ZONE_THE_CHURNING_MISTS = ZONES.ZONE_THE_CHURNING_MISTS
EorzeaWeather.ZONE_THE_CRYSTARIUM = ZONES.ZONE_THE_CRYSTARIUM
EorzeaWeather.ZONE_THE_DIADEM = ZONES.ZONE_THE_DIADEM
EorzeaWeather.ZONE_THE_DRAVANIAN_FORELANDS = ZONES.ZONE_THE_DRAVANIAN_FORELANDS
EorzeaWeather.ZONE_THE_DRAVANIAN_HINTERLANDS = ZONES.ZONE_THE_DRAVANIAN_HINTERLANDS
EorzeaWeather.ZONE_THE_FRINGES = ZONES.ZONE_THE_FRINGES
EorzeaWeather.ZONE_THE_GOBLET = ZONES.ZONE_THE_GOBLET
EorzeaWeather.ZONE_THE_LAVENDER_BEDS = ZONES.ZONE_THE_LAVENDER_BEDS
EorzeaWeather.ZONE_THE_LOCHS = ZONES.ZONE_THE_LOCHS
EorzeaWeather.ZONE_THE_PEAKS = ZONES.ZONE_THE_PEAKS
EorzeaWeather.ZONE_THE_RAKTIKA_GREATWOOD = ZONES.ZONE_THE_RAKTIKA_GREATWOOD
EorzeaWeather.ZONE_THE_RUBY_SEA = ZONES.ZONE_THE_RUBY_SEA
EorzeaWeather.ZONE_THE_SEA_OF_CLOUDS = ZONES.ZONE_THE_SEA_OF_CLOUDS
EorzeaWeather.ZONE_THE_TEMPEST = ZONES.ZONE_THE_TEMPEST
EorzeaWeather.ZONE_ULDAH = ZONES.ZONE_ULDAH
EorzeaWeather.ZONE_UPPER_LA_NOSCEA = ZONES.ZONE_UPPER_LA_NOSCEA
EorzeaWeather.ZONE_WESTERN_LA_NOSCEA = ZONES.ZONE_WESTERN_LA_NOSCEA
EorzeaWeather.ZONE_WESTERN_THANALAN = ZONES.ZONE_WESTERN_THANALAN
EorzeaWeather.ZONE_WOLVES_DEN_PIER = ZONES.ZONE_WOLVES_DEN_PIER
EorzeaWeather.ZONE_YANXIA = ZONES.ZONE_YANXIA

export default EorzeaWeather
export * as WEATHERS from './consts/weathers'
export * as REGIONS from './consts/regions'
export * as ZONES from './consts/zones'
export * as regions from './regions'
export * as chances from './chances'
