import {
  ZONE_AMH_ARAENG,
  ZONE_AZYS_LLA,
  ZONE_CENTRAL_SHROUD,
  ZONE_CENTRAL_THANALAN,
  ZONE_COERTHAS_CENTRAL_HIGHLANDS,
  ZONE_COERTHAS_WESTERN_HIGHLANDS,
  ZONE_EAST_SHROUD,
  ZONE_EASTERN_LA_NOSCEA,
  ZONE_EASTERN_THANALAN,
  ZONE_EULMORE,
  ZONE_EUREKA_ANEMOS,
  ZONE_EUREKA_HYDATOS,
  ZONE_EUREKA_PAGOS,
  ZONE_EUREKA_PYROS,
  ZONE_GRIDANIA,
  ZONE_IDYLLSHIRE,
  ZONE_IL_MHEG,
  ZONE_ISHGARD,
  ZONE_KHOLUSIA,
  ZONE_KUGANE,
  ZONE_LAKELAND,
  ZONE_LIMSA_LOMINSA,
  ZONE_LOWER_LA_NOSCEA,
  ZONE_MIDDLE_LA_NOSCEA,
  ZONE_MIST,
  ZONE_MOR_DHONA,
  ZONE_NORTH_SHROUD,
  ZONE_NORTHERN_THANALAN,
  ZONE_OUTER_LA_NOSCEA,
  ZONE_RHALGRS_REACH,
  ZONE_SHIROGANE,
  ZONE_SOUTH_SHROUD,
  ZONE_SOUTHERN_THANALAN,
  ZONE_THE_AZIM_STEPPE,
  ZONE_THE_BOZJAN_SOUTHERN_FRONT,
  ZONE_THE_CHURNING_MISTS,
  ZONE_THE_CRYSTARIUM,
  ZONE_THE_DIADEM,
  ZONE_THE_DRAVANIAN_FORELANDS,
  ZONE_THE_DRAVANIAN_HINTERLANDS,
  ZONE_THE_FRINGES,
  ZONE_THE_GOBLET,
  ZONE_THE_LAVENDER_BEDS,
  ZONE_THE_LOCHS,
  ZONE_THE_PEAKS,
  ZONE_THE_RAKTIKA_GREATWOOD,
  ZONE_THE_RUBY_SEA,
  ZONE_THE_SEA_OF_CLOUDS,
  ZONE_THE_TEMPEST,
  ZONE_ULDAH,
  ZONE_UPPER_LA_NOSCEA,
  ZONE_WESTERN_LA_NOSCEA,
  ZONE_WESTERN_THANALAN,
  ZONE_WOLVES_DEN_PIER,
  ZONE_YANXIA
} from './consts/zones'

export const eureka = [
  ZONE_EUREKA_ANEMOS,
  ZONE_EUREKA_PAGOS,
  ZONE_EUREKA_PYROS,
  ZONE_EUREKA_HYDATOS
]

export const gyrAbania = [
  ZONE_RHALGRS_REACH,
  ZONE_THE_FRINGES,
  ZONE_THE_PEAKS,
  ZONE_THE_LOCHS
]

export const ishgardAndSurroundingAreas = [
  ZONE_ISHGARD,
  ZONE_COERTHAS_CENTRAL_HIGHLANDS,
  ZONE_COERTHAS_WESTERN_HIGHLANDS,
  ZONE_THE_SEA_OF_CLOUDS,
  ZONE_AZYS_LLA,
  ZONE_IDYLLSHIRE,
  ZONE_THE_DRAVANIAN_FORELANDS,
  ZONE_THE_DRAVANIAN_HINTERLANDS,
  ZONE_THE_CHURNING_MISTS
]

export const laNoscea = [
  ZONE_LIMSA_LOMINSA,
  ZONE_MIDDLE_LA_NOSCEA,
  ZONE_LOWER_LA_NOSCEA,
  ZONE_EASTERN_LA_NOSCEA,
  ZONE_WESTERN_LA_NOSCEA,
  ZONE_UPPER_LA_NOSCEA,
  ZONE_OUTER_LA_NOSCEA,
  ZONE_WOLVES_DEN_PIER
]

export const norvrandt = [
  ZONE_THE_CRYSTARIUM,
  ZONE_EULMORE,
  ZONE_LAKELAND,
  ZONE_KHOLUSIA,
  ZONE_AMH_ARAENG,
  ZONE_IL_MHEG,
  ZONE_THE_RAKTIKA_GREATWOOD,
  ZONE_THE_TEMPEST
]

export const others = [
  ZONE_MOR_DHONA,
  ZONE_MIST,
  ZONE_THE_LAVENDER_BEDS,
  ZONE_THE_GOBLET,
  ZONE_SHIROGANE,
  ZONE_THE_DIADEM,
  ZONE_THE_BOZJAN_SOUTHERN_FRONT
]

export const thanalan = [
  ZONE_ULDAH,
  ZONE_WESTERN_THANALAN,
  ZONE_CENTRAL_THANALAN,
  ZONE_EASTERN_THANALAN,
  ZONE_SOUTHERN_THANALAN,
  ZONE_NORTHERN_THANALAN
  // ZONE_GOLD_SAUCER
]

export const theBlackShroud = [
  ZONE_GRIDANIA,
  ZONE_CENTRAL_SHROUD,
  ZONE_EAST_SHROUD,
  ZONE_SOUTH_SHROUD,
  ZONE_NORTH_SHROUD
]

export const theFarEast = [
  ZONE_KUGANE,
  ZONE_THE_RUBY_SEA,
  ZONE_YANXIA,
  ZONE_THE_AZIM_STEPPE
  // ZONE_THE_DOMAN_ENCLAVE
]
